export const mapas = {
  grieta:
    'El Campo de la Justicia más antiguo y venerado se conoce como Grieta del Invocador. Este campo de batalla es conocido por los constantes conflictos que se libran entre dos grupos opuestos de Invocadores. Recorre uno de los tres caminos diferentes para atacar a tu enemigo en su punto más débil. ¡Trabaja con tus aliados para asediar la base enemiga y destruir su Nexus! Hay tres rutas principales en Summoners Rift, a saber: carril superior, carril central y carril inferior. Cada carril tiene dos torretas exteriores y campeones asignados . El carril superior está formado por campeones de combate cuerpo a cuerpo, luchadores , asesinos y matones , o comúnmente conocidos como AD. El carril central está formado por magos o portadores de AP. El carril inferior está formado por tiradores o ADC, soportes y tanques . La jungla es una subcarril donde se asigna a los junglas para controlar las ventajas y preparar emboscadas .',
  twisted:
    'Si bien los nuevos jugadores probablemente nunca antes hayan oído hablar de Twisted Treeline, cuando Riot Games eliminó el modo de juego hace casi tres años, el mapa clásico 3v3 tenía una comunidad dedicada de jugadores a quienes les encantaba. Twisted Treeline fue diseñado con un estilo completamente diferente al de otros mapas de League of Legends, con dos carriles y una porción de jungla junto a su "Baron Nashor", el Vilemaw.',
  magma:
    'El Abismo de los Lamentos no es en realidad el único mapa de un solo carril en la historia de League of Legends. En 2013, Riot Games reveló un mapa inédito llamado Magma Chamber. Este fue diseñado originalmente como otro mapa de estilo 5v5 con una sensación diferente a Summoners Rift, pero nunca estuvo disponible para el público. A pesar de muchas solicitudes de la comunidad, la única vez que vimos la Cámara de Magma fue durante partes del evento All-Star de 2013. Hasta el día de hoy, los jugadores mantienen la esperanza de tener la oportunidad de jugar en la Cámara de Magma como un mapa 1 contra 1 en League of Legend',
  dominion:
      'El último mapa diferente de League of Legends que los jugadores pueden recordar es Crystal Scar del modo de juego Dominion. Si bien Riot deshabilitó el modo Dominion original en 2016, los jugadores aún pueden acceder al mapa Crystal Scar durante los modos de juego rotativos Ascension y Definitely not Dominion. Para los jugadores que no están familiarizados con el modo de juego Dominion, era efectivamente la versión de League of Legends de Capture the Flag. Los jugadores compiten para capturar los cinco puntos del mapa, reduciendo los puntos totales del equipo enemigo. Después de ganar la mayoría de los puntos, el contador de los equipos contrarios disminuye y continúa disminuyendo aún más rápido cuando se capturan más puntos simultáneamente.'
};
